site_name: App de Saludo con Streamlit
site_url: https://martii03.github.io/App-Streamlit/
repo_url: https://github.com/martii03/App-Streamlit
repo_name: martii03/App-Streamlit

theme:
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.highlight

nav:
  - Inicio: index.md
  - Detalles Técnicos: stapp.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg 